CREATE TABLE R(A INT, B INT, C INT, D INT, E INT, F INT);
CREATE TABLE F(x VARCHAR(10), y VARCHAR(10), violation BOOLEAN, motivation VARCHAR(200));

CREATE TABLE R1(D INT, E INT);
CREATE TABLE F1(x VARCHAR(10), y VARCHAR(10), violation BOOLEAN, motivation VARCHAR(200));

CREATE TABLE R2(A INT, B INT, C INT, E INT, F INT);
CREATE TABLE F2(x VARCHAR(10), y VARCHAR(10), violation BOOLEAN, motivation VARCHAR(200));

CREATE TABLE R3(B INT, C INT, E INT, F INT);
CREATE TABLE F3(x VARCHAR(10), y VARCHAR(10), violation BOOLEAN, motivation VARCHAR(200));

CREATE TABLE R4(A INT, E INT);
CREATE TABLE F4(x VARCHAR(10), y VARCHAR(10), violation BOOLEAN, motivation VARCHAR(200));
